export const SET_NUMBER = "SET_NUMBER"
export const SET_OPERATOR = "SET_OPERATOR"
export const CALCULATE = "CALCULATE"
export const CLEAR = "CLEAR"
export const SET_DECIMAL = "SET_DECIMAL"
export const DEL = "DEL"